# `my_postgres:25512d8:docker_compose.yml:1`.

# https://docs.docker.com/compose/compose-file/

services:
    fmv1992_database_postgres:
        image: postgres@sha256:7211ad97f0ee411fc15fdde06671c38f735273c3933b5ee8b9d169e07d82303f
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
    fmv1992_database_client:
        build:
            context: "./"
            dockerfile: ./dockerfile
            args:
                project: "${PROJECT}"
                gid: "${GID}"
                uid: "${UID}"
        environment:
            ALEMBIC_MESSAGE: "${ALEMBIC_MESSAGE}"
            ALEMBIC_TARGET_ID: "${ALEMBIC_TARGET_ID}"
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        hostname: fmv1992_database_client
        links:
            - fmv1992_database_postgres
        depends_on:
            - fmv1992_database_postgres
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        volumes:
            - type: bind
              source: "${ROOT_DIR}/requirements.txt"
              target: "/home/ubuntu/${PROJECT}/requirements.txt"
              read_only: false
            - type: bind
              source: "${ROOT_DIR}/requirements_all.txt"
              target: "/home/ubuntu/${PROJECT}/requirements_all.txt"
              read_only: false
            - type: bind
              source: "${ROOT_DIR}/code"
              target: "/home/ubuntu/${PROJECT}/code"
              read_only: false
        entrypoint: ""
        command: bash

volumes:
    fmv1992_database_volume:

# vim: set filetype=yaml fileformat=unix nowrap spell spelllang=en shiftwidth=4:
