# `my_postgres:25512d8:docker_compose.yml:1`.

# https://docs.docker.com/compose/compose-file/

version: '3.2'
services:
    postgres_server:
        build:
            context: "./"
            dockerfile: code/docker/dockerfile_server
            args:
                _PGDATA: "${PGDATA}"
                PROJECT: "${PROJECT}"
        restart: always
        hostname: postgres_server
        ports:
            - "1992:5432"
        volumes:
            - pgdata:${PGDATA}
    postgres_client:
        build:
            context: "./"
            dockerfile: code/docker/dockerfile_client
            args:
                PROJECT: "${PROJECT}"
        environment:
            - POSTGRES_PASSWORD=admin
        hostname: postgres_client
        links:
            - postgres_server
        depends_on:
            - postgres_server
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        volumes:
            - type: bind
              source: "${FINANCIAL_DATA}"
              target: "/home/user/${PROJECT}/mount_points/input"
              read_only: true
            - type: bind
              source: "${ROOT_DIR}/code/alembic"
              target: "/home/user/${PROJECT}/code/alembic"
              read_only: false
            - type: bind
              source: "${ROOT_DIR}/output/backups"
              target: "/home/user/${PROJECT}/output/backups"
              read_only: false
            - type: bind
              source: "${ROOT_DIR}/code/postgres/psql_history"
              target: "/root/.psql_history"
              read_only: false
        entrypoint: ""
        command: ""

volumes:
    # ???: Change this to `my_postgres_pgdata`.
    pgdata:

# Make it work with `forticlient VPN`.
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.58.0/24
