"""Create the `book` table.

Revision ID: 41f5c984056c
Revises: aaaaaaaaaaaa
Create Date: 2022-09-07 13:57:49.705995

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = "41f5c984056c"
down_revision = "aaaaaaaaaaaa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("isbn13", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("citation_abbreviation", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("isbn13"),
        schema="fmv1992_books",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book", schema="fmv1992_books")
    # ### end Alembic commands ###
