"""Create the `IdToBlob` table.

Revision ID: d2530ff7f901
Revises: 7e64e2a8f778
Create Date: 2022-07-28 11:31:18.306369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d2530ff7f901"
down_revision = "7e64e2a8f778"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "id_to_binary",
        sa.Column(
            "id",
            sa.String(length=32),
            nullable=False,
            comment="Unique ID of every primary blob.\n\nI decided to use `xxHash` for its collision resistance and speed.\n\nHash example: `32` (`fmv1992_backup_system:7ec185b:pyproject.toml:1`).\n\n# Related links:\n\n1.  <https://github.com/Cyan4973/xxHash>.",
        ),
        sa.Column("binary", sa.LargeBinary(), nullable=False),
        sa.Column("is_compressed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "access_record",
        sa.Column(
            "id",
            sa.String(length=32),
            nullable=False,
            comment="Unique ID of every primary blob.\n\nI decided to use `xxHash` for its collision resistance and speed.\n\nHash example: `32` (`fmv1992_backup_system:7ec185b:pyproject.toml:1`).\n\n# Related links:\n\n1.  <https://github.com/Cyan4973/xxHash>.",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=datetime.timezone.utc),
            nullable=False,
            comment="Timestamp associated with the backed up file/binary blob.",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["id_to_binary.id"],
        ),
        sa.PrimaryKeyConstraint("id", "timestamp"),
    )
    op.create_table(
        "backups",
        sa.Column(
            "id",
            sa.String(length=32),
            nullable=False,
            comment="Unique ID of every primary blob.\n\nI decided to use `xxHash` for its collision resistance and speed.\n\nHash example: `32` (`fmv1992_backup_system:7ec185b:pyproject.toml:1`).\n\n# Related links:\n\n1.  <https://github.com/Cyan4973/xxHash>.",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=datetime.timezone.utc),
            nullable=False,
            comment="Timestamp associated with the backed up file/binary blob.",
        ),
        sa.Column("path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["id_to_binary.id"],
        ),
        sa.PrimaryKeyConstraint("id", "timestamp", "path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backups")
    op.drop_table("access_record")
    op.drop_table("id_to_binary")
    # ### end Alembic commands ###
